// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSm_GY7EHhFy-ePv3d8qWSKjz8cWUsVHE',
    appId: '1:560858568916:web:aaaca2f1e9d46d40f7c341',
    messagingSenderId: '560858568916',
    projectId: 'general-knowledge-32e63',
    authDomain: 'general-knowledge-32e63.firebaseapp.com',
    storageBucket: 'general-knowledge-32e63.appspot.com',
    measurementId: 'G-FR31DJ3NS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADhXbX-8oqTK5zkQUpRl535jpLpLqnSGE',
    appId: '1:560858568916:android:6e27e4c2c5ec3051f7c341',
    messagingSenderId: '560858568916',
    projectId: 'general-knowledge-32e63',
    storageBucket: 'general-knowledge-32e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNeOmwhGmSmnMDlfh7EEWGjpoo_xQ76E8',
    appId: '1:560858568916:ios:052295230cfdec3cf7c341',
    messagingSenderId: '560858568916',
    projectId: 'general-knowledge-32e63',
    storageBucket: 'general-knowledge-32e63.appspot.com',
    iosClientId: '560858568916-rdiqvnjg1rjg56v23ppfs1dia79q8hqs.apps.googleusercontent.com',
    iosBundleId: 'n',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNeOmwhGmSmnMDlfh7EEWGjpoo_xQ76E8',
    appId: '1:560858568916:ios:052295230cfdec3cf7c341',
    messagingSenderId: '560858568916',
    projectId: 'general-knowledge-32e63',
    storageBucket: 'general-knowledge-32e63.appspot.com',
    iosClientId: '560858568916-rdiqvnjg1rjg56v23ppfs1dia79q8hqs.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
